services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./db:/var/www/html/db
      - ./logos:/var/www/html/images/uploads/logos
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallos.rule=Host(`wallos.${DOMAIN}`)"
      - "traefik.http.routers.wallos.service=wallos"
      - "traefik.http.services.wallos.loadbalancer.server.port=80"
      - "homepage.group=Services"
      - "homepage.name=Wallos"
      - "homepage.icon=wallos.png"
      - "homepage.href=https://wallos.${DOMAIN}"
      
networks:
  proxy:
    external: true


